#version 450
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
layout(local_size_x=64) in;
layout(buffer_reference, std430, buffer_reference_align=4) buffer Data { uint values[]; };
layout(push_constant) uniform Parameters { Data data; uint mul; uint add; } p;
void main() {
    uint i=gl_GlobalInvocationID.x;
    p.data.values[i]=(p.data.values[i]^i)*p.mul+p.add;
}
